const barrelIcon = 'https://636c-cloud1-d5gj26hlf342afe88-1433985605.tcb.qcloud.la/images/relicimg/rewardimg/GenericGunPrimeBarrel.png?sign=c2912c9280d7f442361d4a07c768d7ba&t=1779763393'
const receiverIcon = 'https://636c-cloud1-d5gj26hlf342afe88-1433985605.tcb.qcloud.la/images/relicimg/rewardimg/GenericGunPrimeReceiver.png?sign=cdec86e9773d1e9eb2fdd1d5b4381990&t=1779766963'
const latchIcon = 'https://636c-cloud1-d5gj26hlf342afe88-1433985605.tcb.qcloud.la/images/relicimg/rewardimg/GenericComponentPrimeLatch.png?sign=5f6686f768e7b7d7f12231826f7852be&t=1779772486'
const bladeIcon = 'https://636c-cloud1-d5gj26hlf342afe88-1433985605.tcb.qcloud.la/images/relicimg/rewardimg/GenericWeaponPrimeBlade.png?sign=49dc8b92aba21f82b8804741dc3a23e4&t=1779798146'
const stockIcon = 'https://636c-cloud1-d5gj26hlf342afe88-1433985605.tcb.qcloud.la/images/relicimg/rewardimg/GenericGunPrimeStock.png?sign=338901af2bddcd9bb07a80e0756482cb&t=1779800047'
const connectorIcon = 'https://636c-cloud1-d5gj26hlf342afe88-1433985605.tcb.qcloud.la/images/relicimg/rewardimg/GenericComponentPrimePlug.png?sign=aa190e01db6ff3a2cd26def9990777f5&t=1779800366'
const hiltIcon = 'https://636c-cloud1-d5gj26hlf342afe88-1433985605.tcb.qcloud.la/images/relicimg/rewardimg/GenericWeaponPrimeHilt.png?sign=201b16571eaf8c83cffe8c4a10e70dcf&t=1779800858'
const stringIcon = 'https://636c-cloud1-d5gj26hlf342afe88-1433985605.tcb.qcloud.la/images/relicimg/rewardimg/GenericGunPrimeStock.png?sign=95c39ce4a6ec13db0941e9b656716f3c&t=1779801140'
const gripIcon = hiltIcon
const blueprint = 'https://636c-cloud1-d5gj26hlf342afe88-1433985605.tcb.qcloud.la/images/relicimg/rewardimg/blueprint.png?sign=de4363f04aa337ac26b159843c97fa0b&t=1779841474'
const primechassis = 'https://636c-cloud1-d5gj26hlf342afe88-1433985605.tcb.qcloud.la/images/relicimg/rewardimg/PrimeChassis.png?sign=4338f80119b4bf864b86ca53eec94168&t=1779842827'
const primehelmet = 'https://636c-cloud1-d5gj26hlf342afe88-1433985605.tcb.qcloud.la/images/relicimg/rewardimg/PrimeHelmet.png?sign=37c2373e275bed01dacbc392d8f9ced6&t=1779843241'
const primesystems = 'https://636c-cloud1-d5gj26hlf342afe88-1433985605.tcb.qcloud.la/images/relicimg/rewardimg/PrimeSystems.png?sign=78b79a97a7d3f17e1b4b28bf57dd37a3&t=1779844427'
const primeguard = 'https://636c-cloud1-d5gj26hlf342afe88-1433985605.tcb.qcloud.la/images/relicimg/rewardimg/GenericWeaponPrimeGuard.png?sign=d5a5f5c0b013f5a85cb34c08e68d1341&t=1779846363'
const wingschassis = 'https://636c-cloud1-d5gj26hlf342afe88-1433985605.tcb.qcloud.la/images/relicimg/rewardimg/PrimeWingsChassis.png?sign=54139f797feb504960008f77f2317a23&t=1779852646'
const wingssystems = 'https://636c-cloud1-d5gj26hlf342afe88-1433985605.tcb.qcloud.la/images/relicimg/rewardimg/PrimeWingsSystems.png?sign=11eda94b2f2655a8371d8cf9891635b9&t=1779852720'

const rewardItems = [
  { name: '迅发电浆炮Prime枪管', ducats: 45, icon: barrelIcon },
  { name: '迅发电浆炮Prime蓝图', ducats: 100, icon:blueprint},
  { name: '迅发电浆炮Prime枪机', ducats:100, icon: receiverIcon },
  { name: '迅发电浆炮Prime枪托', ducats: 45, icon: stockIcon },
  { name: '盗贼双枪Prime枪管', ducats: 15, icon: barrelIcon },
  { name: '盗贼双枪Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '盗贼双枪Prime连接器', ducats: 100, icon: connectorIcon },
  { name: '盗贼双枪Prime枪机', ducats:45, icon: receiverIcon },
  { name: '阿利乌双枪Prime枪管', ducats: 15, icon: barrelIcon },
  { name: '阿利乌双枪Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '阿利乌双枪Prime连接器', ducats: 100, icon: connectorIcon },
  { name: '阿利乌双枪Prime枪机', ducats:45, icon: receiverIcon },
  { name: '螺钉双枪Prime枪管', ducats: 100, icon: barrelIcon },
  { name: '螺钉双枪Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '螺钉双枪Prime连接器', ducats: 100, icon: connectorIcon },
  { name: '螺钉双枪Prime枪机', ducats:45, icon: receiverIcon },
  { name: '野马双枪Prime蓝图', ducats: 15, icon:blueprint},
  { name: '野马双枪Prime连接器', ducats: 100, icon: connectorIcon },
  { name: '觉醒双枪Prime枪管', ducats: 45, icon: barrelIcon },
  { name: '觉醒双枪Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '觉醒双枪Prime连接器', ducats: 100, icon: connectorIcon },
  { name: '觉醒双枪Prime枪机', ducats:100, icon: receiverIcon },
  { name: '雷克斯双枪Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '雷克斯双枪Prime连接器', ducats: 45, icon: connectorIcon },
  { name: '麦格努斯双枪Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '麦格努斯双枪Prime连接器', ducats: 100, icon: connectorIcon },
  { name: '轻灵月神双枪Prime枪管', ducats: 100, icon: barrelIcon },
  { name: '轻灵月神双枪Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '轻灵月神双枪Prime连接器', ducats: 45, icon: connectorIcon },
  { name: '轻灵月神双枪Prime枪机', ducats:15, icon: receiverIcon },
  { name: '史提托双枪Prime枪管', ducats: 100, icon: barrelIcon },
  { name: '史提托双枪Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '史提托双枪Prime连接器', ducats: 100, icon: connectorIcon },
  { name: '史提托双枪Prime枪机', ducats:100, icon: receiverIcon },
  { name: '瓦斯托双枪Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '瓦斯托双枪Prime连接器', ducats: 100, icon: connectorIcon },
  { name: '电幻步枪Prime枪管', ducats: 100, icon: barrelIcon },
  { name: '电幻步枪Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '电幻步枪Prime枪机', ducats:15, icon: receiverIcon },
  { name: '电幻步枪Prime枪托', ducats: 45, icon: stockIcon },
  { name: '甲龙双拳Prime刀刃', ducats: 100, icon: bladeIcon },
  { name: '甲龙双拳Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '甲龙双拳Prime拳套', ducats: 15, icon: hiltIcon },
  { name: 'Ash Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Ash Prime机体蓝图', ducats: 15 , icon:primechassis},
  { name: 'Ash Prime头部神经光元蓝图', ducats: 100 ,icon:primehelmet},
  { name: 'Ash Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: '碎裂者Prime枪管', ducats: 45, icon: barrelIcon },
  { name: '碎裂者Prime蓝图', ducats: 100, icon:blueprint},
  { name: '碎裂者Prime枪机', ducats:15, icon: receiverIcon },
  { name: '碎裂者Prime枪托', ducats: 100, icon: stockIcon },
  { name: 'Atlas Prime蓝图', ducats: 15 , icon:blueprint},
  { name: 'Atlas Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Atlas Prime头部神经光元蓝图', ducats: 45 ,icon:primehelmet},
  { name: 'Atlas Prime系统蓝图', ducats: 100 ,icon:primesystems},
  { name: '布里斯提卡Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '布里斯提卡Prime下弓臂', ducats: 15 ,icon:bladeIcon},
  { name: '布里斯提卡Prime枪机', ducats:100, icon: receiverIcon },
  { name: '布里斯提卡Prime弓弦', ducats: 100, icon: stringIcon },
  { name: '布里斯提卡Prime上弓臂', ducats: 100 ,icon:bladeIcon},
  { name: 'Banshee Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Banshee Prime机体蓝图', ducats: 45 , icon:primechassis},
  { name: 'Banshee Prime头部神经光元蓝图', ducats: 15 ,icon:primehelmet},
  { name: 'Banshee Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: 'Baruuk Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Baruuk Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Baruuk Prime头部神经光元蓝图', ducats: 45 ,icon:primehelmet},
  { name: 'Baruuk Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: '苍鹰Prime枪管', ducats: 100, icon: barrelIcon },
  { name: '苍鹰Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '苍鹰Prime枪机', ducats:15, icon: receiverIcon },
  { name: '苍鹰Prime枪托', ducats: 45, icon: stockIcon },
  { name: '玻之武杖Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '玻之武杖Prime握柄', ducats: 100, icon: gripIcon },
  { name: '玻之武杖Prime饰物', ducats: 15 ,icon:connectorIcon},
  { name: '野猪Prime枪管', ducats: 100, icon: barrelIcon },
  { name: '野猪Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '野猪Prime枪机', ducats:15, icon: receiverIcon },
  { name: '野猪Prime枪托', ducats: 45, icon: stockIcon },
  { name: '螺钉步枪Prime枪管', ducats: 15, icon: barrelIcon },
  { name: '螺钉步枪Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '螺钉步枪Prime枪机', ducats:100, icon: receiverIcon },
  { name: '螺钉步枪Prime枪托', ducats: 15, icon: stockIcon },
  { name: '布莱顿Prime枪管', ducats: 15, icon: barrelIcon },
  { name: '布莱顿Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '布莱顿Prime枪机', ducats:15, icon: receiverIcon },
  { name: '布莱顿Prime枪托', ducats: 15, icon: stockIcon },
  { name: '野马Prime枪管', ducats: 15, icon: barrelIcon },
  { name: '野马Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '野马Prime枪机', ducats:15, icon: receiverIcon },
  { name: '伯斯顿Prime枪管', ducats: 100, icon: barrelIcon },
  { name: '伯斯顿Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '伯斯顿Prime枪机', ducats:15, icon: receiverIcon },
  { name: '伯斯顿Prime枪托', ducats: 15, icon: stockIcon },
  { name: 'Caliban Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Caliban Prime机体蓝图', ducats: 15 , icon:primechassis},
  { name: 'Caliban Prime头部神经光元蓝图', ducats: 45 ,icon:primehelmet},
  { name: 'Caliban Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: '搬运者Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '搬运者Prime外壳', ducats: 15,icon:primechassis},
  { name: '搬运者Prime头部', ducats: 45 ,icon:primehelmet},
  { name: '搬运者Prime系统', ducats: 15 ,icon:primesystems},
  { name: '塞多Prime枪管', ducats: 100, icon: barrelIcon },
  { name: '塞多Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '塞多Prime枪机', ducats:100, icon: receiverIcon },
  { name: '塞多Prime枪托', ducats: 15, icon: stockIcon },
  { name: '西诺斯Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '西诺斯Prime弓身', ducats: 15, icon: latchIcon },
  { name: '西诺斯Prime下弓臂', ducats: 45 ,icon:bladeIcon},
  { name: '西诺斯Prime弓弦', ducats: 100, icon: stringIcon },
  { name: '西诺斯Prime上弓臂', ducats: 15 ,icon:bladeIcon},
  { name: 'Chroma Prime蓝图', ducats: 15 , icon:blueprint},
  { name: 'Chroma Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Chroma Prime头部神经光元蓝图', ducats: 45 ,icon:primehelmet},
  { name: 'Chroma Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: '眼镜蛇&鹤Prime刀刃', ducats: 100, icon: bladeIcon },
  { name: '眼镜蛇&鹤Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '眼镜蛇&鹤Prime护手', ducats: 45 ,icon:primeguard},
  { name: '眼镜蛇&鹤Prime握柄', ducats: 15, icon: gripIcon , icon: gripIcon},
  { name: '科林斯Prime枪管', ducats: 45, icon: barrelIcon },
  { name: '科林斯Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '科林斯Prime枪机', ducats:100, icon: receiverIcon },
  { name: '科林斯Prime枪托', ducats: 45, icon: stockIcon },
  { name: '黑鸦Prime枪管', ducats: 45, icon: barrelIcon },
  { name: '黑鸦Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '黑鸦Prime枪机', ducats:15, icon: receiverIcon },
  { name: '黑鸦Prime枪托', ducats: 15, icon: stockIcon },
  { name: '大久和弓Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '大久和弓Prime弓身', ducats: 45, icon: latchIcon },
  { name: '大久和弓Prime下弓臂', ducats: 100 ,icon:bladeIcon},
  { name: '大久和弓Prime弓弦', ducats: 15, icon: stringIcon },
  { name: '大久和弓Prime上弓臂', ducats: 100 ,icon:bladeIcon},
  { name: '达克拉Prime刀刃', ducats: 45, icon: bladeIcon },
  { name: '达克拉Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '达克拉Prime握柄', ducats: 15, icon: gripIcon },
  { name: '技巧之剑Prime刀刃', ducats: 45, icon: bladeIcon },
  { name: '技巧之剑Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '技巧之剑Prime握柄', ducats: 15, icon: gripIcon },
  { name: '死亡魔方Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '死亡魔方Prime外壳', ducats: 100 ,icon:primechassis},
  { name: '死亡魔方Prime头部', ducats: 45 ,icon:primehelmet},
  { name: '死亡魔方Prime系统', ducats: 15 ,icon:primesystems},
  { name: '双短柄战镰Prime刀刃', ducats: 45, icon: bladeIcon },
  { name: '双短柄战镰Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '双短柄战镰Prime握柄', ducats: 100, icon: gripIcon },
  { name: '凯瑞斯双刀Prime刀刃', ducats: 15, icon: bladeIcon },
  { name: '凯瑞斯双刀Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '凯瑞斯双刀Prime握柄', ducats: 100, icon: gripIcon },
  { name: '佐伦双斧Prime刀刃', ducats: 45, icon: bladeIcon },
  { name: '佐伦双斧Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '佐伦双斧Prime握柄', ducats: 15, icon: gripIcon },
  { name: 'Ember Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Ember Prime机体蓝图', ducats: 15 , icon:primechassis},
  { name: 'Ember Prime头部神经光元蓝图', ducats: 15 ,icon:primehelmet},
  { name: 'Ember Prime系统蓝图', ducats: 100 ,icon:primesystems},
  { name: '葬铭Prime枪管', ducats: 100, icon: barrelIcon },
  { name: '葬铭Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '葬铭Prime枪机', ducats:45, icon: receiverIcon },
  { name: 'Equinox Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Equinox Prime机体蓝图', ducats: 15 , icon:primechassis},
  { name: 'Equinox Prime头部神经光元蓝图', ducats: 100 ,icon:primehelmet},
  { name: 'Equinox Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: '悦音Prime枪管', ducats: 100, icon: barrelIcon },
  { name: '悦音Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '悦音Prime枪机', ducats:45, icon: receiverIcon },
  { name: '狼牙Prime刀刃', ducats: 15, icon: bladeIcon },
  { name: '狼牙Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '狼牙Prime握柄', ducats: 15, icon: gripIcon },
  { name: 'Forma蓝图', ducats: 15 , icon:blueprint},
  { name: '重击巨锤Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '重击巨锤Prime握柄', ducats: 45, icon: gripIcon },
  { name: '重击巨锤Prime锤头', ducats: 15 ,icon:bladeIcon},
  { name: 'Frost Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Frost Prime机体蓝图', ducats: 15 , icon:primechassis},
  { name: 'Frost Prime头部神经光元蓝图', ducats: 15 ,icon:primehelmet},
  { name: 'Frost Prime系统蓝图', ducats: 100 ,icon:primesystems},
  { name: '雷霆Prime枪管', ducats: 15, icon: barrelIcon },
  { name: '雷霆Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '雷霆Prime枪机', ducats:45, icon: receiverIcon },
  { name: '雷霆Prime枪托', ducats: 100, icon: stockIcon },
  { name: '迦伦提恩Prime刀刃', ducats: 15, icon: bladeIcon },
  { name: '迦伦提恩Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '迦伦提恩Prime握柄', ducats: 100, icon: gripIcon },
  { name: 'Gara Prime蓝图', ducats: 45, icon:blueprint },
  { name: 'Gara Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Gara Prime头部神经光元蓝图', ducats: 100 ,icon:primehelmet},
  { name: 'Gara Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: 'Garuda Prime蓝图', ducats: 15 , icon:blueprint},
  { name: 'Garuda Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Garuda Prime头部神经光元蓝图', ducats: 45 ,icon:primehelmet},
  { name: 'Garuda Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: 'Gauss Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Gauss Prime机体蓝图', ducats: 15 , icon:primechassis},
  { name: 'Gauss Prime头部神经光元蓝图', ducats: 100 ,icon:primehelmet},
  { name: 'Gauss Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: '战刃Prime刀刃', ducats: 100, icon: bladeIcon },
  { name: '战刃Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '战刃Prime圆盘', ducats: 100 ,icon:bladeIcon},
  { name: '格拉姆Prime刀刃', ducats: 15, icon: bladeIcon },
  { name: '格拉姆Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '格拉姆Prime握柄', ducats: 45, icon: gripIcon },
  { name: 'Grendel Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Grendel Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Grendel Prime头部神经光元蓝图', ducats: 15 ,icon:primehelmet},
  { name: 'Grendel Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: '关刀Prime刀刃', ducats: 15, icon: bladeIcon },
  { name: '关刀Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '关刀Prime握柄', ducats: 45, icon: gripIcon },
  { name: '军扇Prime刀刃', ducats: 45, icon: bladeIcon },
  { name: '军扇Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '军扇Prime握柄', ducats: 100, icon: gripIcon },
  { name: 'Gyre Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Gyre Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Gyre Prime头部神经光元蓝图', ducats: 45 ,icon:primehelmet},
  { name: 'Gyre Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: 'Harrow Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Harrow Prime机体蓝图', ducats: 15 , icon:primechassis},
  { name: 'Harrow Prime头部神经光元蓝图', ducats: 100 ,icon:primehelmet},
  { name: 'Harrow Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: '赫利俄斯 Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '赫利俄斯 Prime外壳', ducats: 15 ,icon:primechassis},
  { name: '赫利俄斯 Prime头部', ducats: 45 ,icon:primehelmet},
  { name: '赫利俄斯 Prime系统', ducats: 100 ,icon:primesystems},
  { name: '飞扬Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '飞扬Prime镖袋', ducats: 15 ,icon:connectorIcon},
  { name: '飞扬Prime星镖', ducats: 15 ,icon:bladeIcon},
  { name: 'Hildryn Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Hildryn Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Hildryn Prime头部神经光元蓝图', ducats: 100 ,icon:primehelmet},
  { name: 'Hildryn Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: 'Hydroid Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Hydroid Prime机体蓝图', ducats: 15 , icon:primechassis},
  { name: 'Hydroid Prime头部神经光元蓝图', ducats: 100 ,icon:primehelmet},
  { name: 'Hydroid Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: '豪猪Prime枪管', ducats: 15, icon: barrelIcon },
  { name: '豪猪Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '豪猪Prime枪机', ducats:45, icon: receiverIcon },
  { name: 'Inaros Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Inaros Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Inaros Prime头部神经光元蓝图', ducats: 45 ,icon:primehelmet},
  { name: 'Inaros Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: 'Ivara Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Ivara Prime机体蓝图', ducats: 45 , icon:primechassis},
  { name: 'Ivara Prime头部神经光元蓝图', ducats: 15 ,icon:primehelmet},
  { name: 'Ivara Prime系统蓝图', ducats: 100 ,icon:primesystems},
  { name: '凯洛斯特Prime刀刃', ducats: 45, icon: bladeIcon },
  { name: '凯洛斯特Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '凯洛斯特Prime握柄', ducats: 100 , icon: gripIcon},
  { name: '喀婆萨Prime项圈带', ducats: 100 ,icon:latchIcon},
  { name: '喀婆萨Prime项圈扣', ducats: 45 ,icon:connectorIcon},
  { name: 'Kubrow Collar Blueprint', ducats: 100 , icon:blueprint},
  { name: '红隼Prime刀刃', ducats: 15, icon: bladeIcon },
  { name: '红隼Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '红隼Prime弓身', ducats: 45, icon: latchIcon },
  { name: 'Khora Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Khora Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Khora Prime头部神经光元蓝图', ducats: 45 ,icon:primehelmet},
  { name: 'Khora Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: '丧钟Prime枪管', ducats: 45 , icon: barrelIcon},
  { name: '丧钟Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '丧钟Prime枪机', ducats:45, icon: receiverIcon },
  { name: '科加基Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '科加基Prime靴子', ducats: 15 ,icon:primeguard},
  { name: '科加基Prime拳套', ducats: 45, icon: hiltIcon },
  { name: '卡帕压力枪Prime枪管', ducats: 45 , icon: barrelIcon},
  { name: '卡帕压力枪Prime蓝图', ducats: 15, icon:blueprint},
  { name: '卡帕压力枪Prime枪机', ducats:100, icon: receiverIcon },
  { name: '皇家拐刃Prime刀刃', ducats: 45, icon: bladeIcon },
  { name: '皇家拐刃Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '皇家拐刃Prime握柄', ducats: 100 , icon: gripIcon},
  { name: '翠雀Prime枪管', ducats: 45 , icon: barrelIcon},
  { name: '翠雀Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '翠雀Prime枪机', ducats:100, icon: receiverIcon },
  { name: '翠雀Prime枪托', ducats: 100, icon: stockIcon },
  { name: '拉特昂Prime枪管', ducats: 15, icon: barrelIcon},
  { name: '拉特昂Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '拉特昂Prime枪机', ducats:15, icon: receiverIcon },
  { name: '拉特昂Prime枪托', ducats: 15, icon: stockIcon },
  { name: 'Lavos Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Lavos Prime机体蓝图', ducats: 15 , icon:primechassis},
  { name: 'Lavos Prime头部神经光元蓝图', ducats: 100 ,icon:primehelmet},
  { name: 'Lavos Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: '雷克斯Prime枪管', ducats: 15, icon: barrelIcon },
  { name: '雷克斯Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '雷克斯Prime枪机', ducats:15, icon: receiverIcon },
  { name: 'Limbo Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Limbo Prime机体蓝图', ducats: 45 , icon:primechassis},
  { name: 'Limbo Prime头部神经光元蓝图', ducats: 45 ,icon:primehelmet},
  { name: 'Limbo Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: 'Loki Prime蓝图', ducats: 15 , icon:blueprint},
  { name: 'Loki Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Loki Prime头部神经光元蓝图', ducats: 15 ,icon:primehelmet},
  { name: 'Loki Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: 'Mag Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Mag Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Mag Prime头部神经光元蓝图', ducats: 15 ,icon:primehelmet},
  { name: 'Mag Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: '麦格努斯Prime枪管', ducats: 45, icon: barrelIcon },
  { name: '麦格努斯Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '麦格努斯Prime枪机', ducats:100, icon: receiverIcon },
  { name: '咀嚼金杖Prime刀刃', ducats: 45, icon: bladeIcon },
  { name: '咀嚼金杖Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '咀嚼金杖Prime握柄', ducats: 15 , icon: gripIcon},
  { name: 'Mesa Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Mesa Prime机体蓝图', ducats: 15 , icon:primechassis},
  { name: 'Mesa Prime头部神经光元蓝图', ducats: 45 ,icon:primehelmet},
  { name: 'Mesa Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: 'Mirage Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Mirage Prime机体蓝图', ducats: 15 , icon:primechassis},
  { name: 'Mirage Prime头部神经光元蓝图', ducats: 15 ,icon:primehelmet},
  { name: 'Mirage Prime系统蓝图', ducats: 100 ,icon:primesystems},
  { name: '噬蛇弩Prime枪管', ducats: 15, icon: barrelIcon },
  { name: '噬蛇弩Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '噬蛇弩Prime枪机', ducats:100, icon: receiverIcon },
  { name: '噬蛇弩Prime枪托', ducats: 100, icon: stockIcon },
  { name: '海波斯库拉对剑Prime刀刃', ducats: 45, icon: bladeIcon },
  { name: '海波斯库拉对剑Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '海波斯库拉对剑Prime握柄', ducats: 100 , icon: gripIcon},
  { name: '鹦鹉螺Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '鹦鹉螺Prime外壳', ducats: 15 ,icon:primechassis},
  { name: '鹦鹉螺Prime头部', ducats: 45 ,icon:primehelmet},
  { name: '鹦鹉螺Prime系统', ducats: 100 ,icon:primesystems},
  { name: '鹦鹉螺Prime系统蓝图', ducats: 100 ,icon:primesystems},
  { name: 'Nekros Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Nekros Prime机体蓝图', ducats: 15 , icon:primechassis},
  { name: 'Nekros Prime头部神经光元蓝图', ducats: 100 ,icon:primehelmet},
  { name: 'Nekros Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: 'Nezha Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Nezha Prime机体蓝图', ducats: 45 , icon:primechassis},
  { name: 'Nezha Prime头部神经光元蓝图', ducats: 45 ,icon:primehelmet},
  { name: 'Nezha Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: 'Nidus Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Nidus Prime机体蓝图', ducats: 45 , icon:primechassis},
  { name: 'Nidus Prime头部神经光元蓝图', ducats: 45 ,icon:primehelmet},
  { name: 'Nidus Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: '侍刃Prime刀刃', ducats: 45, icon: bladeIcon },
  { name: '侍刃Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '侍刃Prime握柄', ducats: 45 , icon: gripIcon},
  { name: '降灵追猎者Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '降灵追猎者Prime链条', ducats: 100 ,icon:stockIcon},
  { name: '降灵追猎者Prime握柄', ducats: 45 , icon: gripIcon},
  { name: 'Nova Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Nova Prime机体蓝图', ducats: 45 , icon:primechassis},
  { name: 'Nova Prime头部神经光元蓝图', ducats: 15 ,icon:primehelmet},
  { name: 'Nova Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: 'Nyx Prime蓝图', ducats: 15 , icon:blueprint},
  { name: 'Nyx Prime机体蓝图', ducats: 45 , icon:primechassis},
  { name: 'Nyx Prime头部神经光元蓝图', ducats: 45 ,icon:primehelmet},
  { name: 'Nyx Prime系统蓝图', ducats: 100 ,icon:primesystems},
  { name: 'Oberon Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Oberon Prime机体蓝图', ducats: 15 , icon:primechassis},
  { name: 'Oberon Prime头部神经光元蓝图', ducats: 45 ,icon:primehelmet},
  { name: 'Oberon Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: 'Octavia Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Octavia Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Octavia Prime头部神经光元蓝图', ducats: 15 ,icon:primehelmet},
  { name: 'Octavia Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: '陨蜓Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '陨蜓Prime外甲蓝图', ducats: 15 ,icon:wingschassis},
  { name: '陨蜓Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: '陨蜓Prime机翼蓝图', ducats: 45 ,icon:wingssystems},
  { name: '翁Prime刀刃', ducats: 15, icon: bladeIcon },
  { name: '翁Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '翁Prime握柄', ducats: 100 , icon: gripIcon},
  { name: '欧特鲁斯Prime刀刃', ducats: 100, icon: bladeIcon },
  { name: '欧特鲁斯Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '欧特鲁斯Prime握柄', ducats: 15 , icon: gripIcon},
  { name: '手鼓Prime枪管', ducats: 100 , icon: barrelIcon},
  { name: '手鼓Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '手鼓Prime枪机', ducats:45, icon: receiverIcon },
  { name: '鲮鲤剑Prime刀刃', ducats: 100, icon: bladeIcon },
  { name: '鲮鲤剑Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '鲮鲤剑Prime握柄', ducats: 15 , icon: gripIcon},
  { name: '猎豹Prime枪管', ducats: 45 , icon: barrelIcon},
  { name: '猎豹Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '猎豹Prime枪机', ducats:45, icon: receiverIcon },
  { name: '猎豹Prime枪托', ducats: 100, icon: stockIcon },
  { name: '帕里斯Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '帕里斯Prime弓身', ducats: 100, icon: latchIcon },
  { name: '帕里斯Prime下弓臂', ducats: 15 ,icon:bladeIcon},
  { name: '帕里斯Prime弓弦', ducats: 15, icon: stringIcon },
  { name: '帕里斯Prime上弓臂', ducats: 15 ,icon:bladeIcon},
  { name: '月面狂风Prime枪管', ducats: 45 , icon: barrelIcon},
  { name: '月面狂风Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '月面狂风Prime枪机', ducats:100, icon: receiverIcon },
  { name: '月面狂风Prime枪托', ducats: 15, icon: stockIcon },
  { name: '幻离子Prime枪管', ducats: 45 , icon: barrelIcon},
  { name: '幻离子Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '幻离子Prime枪机', ducats:15, icon: receiverIcon },
  { name: '幻离子Prime枪托', ducats: 45, icon: stockIcon },
  { name: 'Protea Prime蓝图', ducats: 15 , icon:blueprint},
  { name: 'Protea Prime机体蓝图', ducats: 45 , icon:primechassis},
  { name: 'Protea Prime头部神经光元蓝图', ducats: 100 ,icon:primehelmet},
  { name: 'Protea Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: '食人鱼Prime枪管', ducats: 15 , icon: barrelIcon},
  { name: '食人鱼Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '食人鱼Prime枪机', ducats:100, icon: receiverIcon },
  { name: '威震武扇Prime刀刃', ducats: 45, icon: bladeIcon },
  { name: '威震武扇Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '威震武扇Prime握柄', ducats: 15 , icon: gripIcon},
  { name: '收割者Prime刀刃', ducats: 100, icon: bladeIcon },
  { name: '收割者Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '收割者Prime握柄', ducats: 15, icon: gripIcon},
  { name: '救赎者Prime刀刃', ducats: 15, icon: bladeIcon },
  { name: '救赎者Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '救赎者Prime握柄', ducats: 45 , icon: gripIcon},
  { name: 'Revenant Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Revenant Prime机体蓝图', ducats: 15 , icon:primechassis},
  { name: 'Revenant Prime头部神经光元蓝图', ducats: 100 ,icon:primehelmet},
  { name: 'Revenant Prime系统蓝图', ducats: 100 ,icon:primesystems},
  { name: 'Rhino Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Rhino Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Rhino Prime头部神经光元蓝图', ducats: 100 ,icon:primehelmet},
  { name: 'Rhino Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: '绝路Prime枪管', ducats: 100 , icon: barrelIcon},
  { name: '绝路Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '绝路Prime枪机', ducats:15, icon: receiverIcon },
  { name: '绝路Prime枪托', ducats: 100, icon: stockIcon },
  { name: '沙罗之牙Prime刀刃', ducats: 45, icon: bladeIcon },
  { name: '沙罗之牙Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '沙罗之牙Prime握柄', ducats: 15 , icon: gripIcon},
  { name: 'Saryn Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Saryn Prime机体蓝图', ducats: 45 , icon:primechassis},
  { name: 'Saryn Prime头部神经光元蓝图', ducats: 100 ,icon:primehelmet},
  { name: 'Saryn Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: '分裂斩斧Prime刀刃', ducats: 45, icon: bladeIcon },
  { name: '分裂斩斧Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '分裂斩斧Prime握柄', ducats: 15 , icon: gripIcon},
  { name: '祸根Prime枪管', ducats: 45 , icon: barrelIcon},
  { name: '祸根Prime刀刃', ducats: 15, icon: bladeIcon },
  { name: '祸根Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '祸根Prime握柄', ducats: 100 , icon: gripIcon},
  { name: 'Sevagoth头部神经光元蓝图', ducats: 15 ,icon:primehelmet},
  { name: 'Sevagoth Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Sevagoth Prime机体蓝图', ducats: 45 , icon:primechassis},
  { name: 'Sevagoth Prime头部神经光元蓝图', ducats: 15 ,icon:primehelmet},
  { name: 'Sevagoth Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: '阴影Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '阴影Prime外壳', ducats: 45 ,icon:primechassis},
  { name: '阴影Prime头部', ducats: 15 ,icon:primehelmet},
  { name: '阴影Prime系统', ducats: 100 ,icon:primesystems},
  { name: '暗杀者Prime枪管', ducats: 15 , icon: barrelIcon},
  { name: '暗杀者Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '暗杀者Prime枪机', ducats:45, icon: receiverIcon },
  { name: '席瓦&神盾Prime刀刃', ducats: 100, icon: bladeIcon },
  { name: '席瓦&神盾Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '席瓦&神盾Prime护手', ducats: 45 ,icon:primeguard},
  { name: '席瓦&神盾Prime握柄', ducats: 15 , icon: gripIcon},
  { name: '月神Prime枪管', ducats: 15 , icon: barrelIcon},
  { name: '月神Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '月神Prime枪机', ducats:100, icon: receiverIcon },
  { name: '月神Prime枪托', ducats: 45, icon: stockIcon },
  { name: '旋刃飞刀Prime刀刃', ducats: 45, icon: bladeIcon },
  { name: '旋刃飞刀Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '旋刃飞刀Prime镖袋', ducats: 45 ,icon:connectorIcon},
  { name: '斯特拉迪瓦Prime枪管', ducats: 100, icon: barrelIcon },
  { name: '斯特拉迪瓦Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '斯特拉迪瓦Prime枪机', ducats:15, icon: receiverIcon },
  { name: '斯特拉迪瓦Prime枪托', ducats: 15, icon: stockIcon },
  { name: '斯特朗Prime枪管', ducats: 100 , icon: barrelIcon},
  { name: '斯特朗Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '斯特朗Prime枪机', ducats:15, icon: receiverIcon },
  { name: '斯特朗Prime枪托', ducats: 100, icon: stockIcon },
  { name: '席芭莉丝Prime枪管', ducats: 45 , icon: barrelIcon},
  { name: '席芭莉丝Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '席芭莉丝Prime枪机', ducats:100, icon: receiverIcon },
  { name: '席芭莉丝Prime枪托', ducats: 15, icon: stockIcon },
  { name: '龙辰Prime刀刃', ducats: 100, icon: bladeIcon },
  { name: '龙辰Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '龙辰Prime握柄', ducats: 45 , icon: gripIcon},
  { name: '铁钩手甲Prime刀刃', ducats: 45, icon: bladeIcon },
  { name: '铁钩手甲Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '铁钩手甲Prime拳套', ducats: 15, icon: hiltIcon },
  { name: '双簧管Prime枪管', ducats: 45 , icon: barrelIcon},
  { name: '双簧管Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '双簧管Prime枪机', ducats:45, icon: receiverIcon },
  { name: '双簧管Prime枪托', ducats: 100, icon: stockIcon },
  { name: '狂鲨Prime枪管', ducats: 45, icon: barrelIcon },
  { name: '狂鲨Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '狂鲨Prime枪机', ducats:15, icon: receiverIcon },
  { name: '狂鲨Prime枪托', ducats: 45, icon: stockIcon },
  { name: '猛虎Prime枪管', ducats: 100 , icon: barrelIcon},
  { name: '猛虎Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '猛虎Prime枪机', ducats:100, icon: receiverIcon },
  { name: '猛虎Prime枪托', ducats: 15, icon: stockIcon },
  { name: '提佩多Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '提佩多Prime握柄', ducats: 45 , icon: gripIcon},
  { name: '提佩多Prime饰物', ducats: 100 ,icon:connectorIcon},
  { name: 'Titania Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Titania Prime机体蓝图', ducats: 15 , icon:primechassis},
  { name: 'Titania Prime头部神经光元蓝图', ducats: 100 ,icon:primehelmet},
  { name: 'Titania Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: 'Trinity Prime蓝图', ducats: 100 , icon:blueprint},
  { name: 'Trinity Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Trinity Prime头部神经光元蓝图', ducats: 15 ,icon:primehelmet},
  { name: 'Trinity Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: '灭杀者Prime枪管', ducats: 45 , icon: barrelIcon},
  { name: '灭杀者Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '灭杀者Prime枪机', ducats:45, icon: receiverIcon },
  { name: '灭杀者Prime枪托', ducats: 100, icon: stockIcon },
  { name: '瓦德雅Prime枪管', ducats: 100 , icon: barrelIcon},
  { name: '瓦德雅Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '瓦德雅Prime枪机', ducats:100, icon: receiverIcon },
  { name: '瓦德雅Prime枪托', ducats: 15, icon: stockIcon },
  { name: 'Valkyr Prime蓝图', ducats: 15 , icon:blueprint},
  { name: 'Valkyr Prime机体蓝图', ducats: 45 , icon:primechassis},
  { name: 'Valkyr Prime头部神经光元蓝图', ducats: 100 ,icon:primehelmet},
  { name: 'Valkyr Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: '瓦斯托Prime枪管', ducats: 15 , icon: barrelIcon},
  { name: '瓦斯托Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '瓦斯托Prime枪机', ducats:15, icon: receiverIcon },
  { name: 'Vauban Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Vauban Prime机体蓝图', ducats: 45 , icon:primechassis},
  { name: 'Vauban Prime头部神经光元蓝图', ducats: 45 ,icon:primehelmet},
  { name: 'Vauban Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: '守望者Prime枪管', ducats: 15 , icon: barrelIcon},
  { name: '守望者Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '守望者Prime枪机', ducats:45, icon: receiverIcon },
  { name: '守望者Prime枪托', ducats: 45, icon: stockIcon },
  { name: '逐电Prime枪管', ducats: 45 , icon: barrelIcon},
  { name: '逐电Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '逐电Prime枪机', ducats:15, icon: receiverIcon },
  { name: '脉纹Prime刀刃', ducats: 45, icon: bladeIcon },
  { name: '脉纹Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '脉纹Prime握柄', ducats: 15 , icon: gripIcon},
  { name: '凯旋之爪Prime爪刃', ducats: 15 ,icon:bladeIcon},
  { name: '凯旋之爪Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '凯旋之爪Prime拳套', ducats: 45, icon: hiltIcon },
  { name: '创伤Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '创伤Prime握柄', ducats: 45 , icon: gripIcon},
  { name: '创伤Prime锤头', ducats: 100 ,icon:bladeIcon},
  { name: 'Volt Prime蓝图', ducats: 15 , icon:blueprint},
  { name: 'Volt Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Volt Prime头部神经光元蓝图', ducats: 45 ,icon:primehelmet},
  { name: 'Volt Prime系统蓝图', ducats: 100 ,icon:primesystems},
  { name: 'Voruna Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Voruna Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Voruna Prime头部神经光元蓝图', ducats: 100 ,icon:primehelmet},
  { name: 'Voruna Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: 'Wisp Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Wisp Prime机体蓝图', ducats: 45 , icon:primechassis},
  { name: 'Wisp Prime头部神经光元蓝图', ducats: 100 ,icon:primehelmet},
  { name: 'Wisp Prime系统蓝图', ducats: 15 ,icon:primesystems},
  { name: 'Wukong Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Wukong Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Wukong Prime头部神经光元蓝图', ducats: 15 ,icon:primehelmet},
  { name: 'Wukong Prime系统蓝图', ducats: 100 ,icon:primesystems},
  { name: '蛟龙 Prime蓝图', ducats: 15 , icon:blueprint},
  { name: '蛟龙 Prime外壳', ducats: 15 ,icon:primechassis},
  { name: '蛟龙 Prime头部', ducats: 15 ,icon:primehelmet},
  { name: '蛟龙 Prime系统', ducats: 100 ,icon:primesystems},
  { name: 'Xaku Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Xaku Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Xaku Prime头部神经光元蓝图', ducats: 15 ,icon:primehelmet},
  { name: 'Xaku Prime系统蓝图', ducats: 100 ,icon:primesystems},
  { name: 'Yareli Prime蓝图', ducats: 100, icon:blueprint },
  { name: 'Yareli Prime机体蓝图', ducats: 15 , icon:primechassis},
  { name: 'Yareli Prime头部神经光元蓝图', ducats: 45 ,icon:primehelmet},
  { name: 'Yareli Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: '毒芽Prime枪管', ducats: 100, icon: barrelIcon },
  { name: '毒芽Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '毒芽Prime枪机', ducats:15, icon: receiverIcon },
  { name: 'Zephyr Prime蓝图', ducats: 45 , icon:blueprint},
  { name: 'Zephyr Prime机体蓝图', ducats: 100 , icon:primechassis},
  { name: 'Zephyr Prime头部神经光元蓝图', ducats: 15 ,icon:primehelmet},
  { name: 'Zephyr Prime系统蓝图', ducats: 45 ,icon:primesystems},
  { name: '诸葛连弩Prime枪管', ducats: 45, icon: barrelIcon },
  { name: '诸葛连弩Prime蓝图', ducats: 100 , icon:blueprint},
  { name: '诸葛连弩Prime弓身', ducats: 15, icon: latchIcon },
  { name: '诸葛连弩Prime枪机', ducats:100, icon: receiverIcon },
  { name: '诸葛连弩Prime弓弦', ducats: 15, icon: stringIcon },
  { name: '席尔火枪Prime枪管', ducats: 15, icon: barrelIcon },
  { name: '席尔火枪Prime蓝图', ducats: 45 , icon:blueprint},
  { name: '席尔火枪Prime枪机', ducats:100, icon: receiverIcon }
]


function buildRows(items, keyword) {
  const normalizedKeyword = keyword.trim().toLowerCase()
  return items.filter((item) => !normalizedKeyword || item.name.toLowerCase().includes(normalizedKeyword))
}

function buildSelectionState(items, selectedCounts) {
  const selectedItems = []
  let selectedTotalDucats = 0

  items.forEach((item) => {
    const count = selectedCounts[item.name] || 0
    if (!count) {
      return
    }

    const subtotal = item.ducats * count
    selectedItems.push({
      name: item.name,
      ducats: item.ducats,
      icon: item.icon,
      count,
      subtotal
    })
    selectedTotalDucats += subtotal
  })

  return { selectedItems, selectedTotalDucats }
}

Page({
  sourceItems: rewardItems,
  selectedCounts: {},
  data: {
    title: '杜卡德计算器',
    searchKeyword: '',
    isSelectionPopupVisible: false,
    selectedItems: [],
    selectedTotalDucats: 0,
    tableHeaders: ['物品名称', '杜卡德金币'],
    rows: []
  },
  onLoad() {
    this.syncRows()
    this.syncSelection()
  },
  handleSearchInput(event) {
    this.setData({
      searchKeyword: event.detail.value
    })
    this.syncRows()
  },
  handleAddItem(event) {
    const { name } = event.currentTarget.dataset
    if (!name) {
      return
    }

    this.selectedCounts[name] = (this.selectedCounts[name] || 0) + 1
    this.syncSelection()
  },
  openSelectionPopup() {
    this.setData({
      isSelectionPopupVisible: true
    })
  },
  closeSelectionPopup() {
    this.setData({
      isSelectionPopupVisible: false
    })
  },
  increaseSelectedItem(event) {
    const { name } = event.currentTarget.dataset
    if (!name) {
      return
    }

    this.selectedCounts[name] = (this.selectedCounts[name] || 0) + 1
    this.syncSelection()
  },
  decreaseSelectedItem(event) {
    const { name } = event.currentTarget.dataset
    if (!name) {
      return
    }

    const nextCount = (this.selectedCounts[name] || 0) - 1
    if (nextCount <= 0) {
      delete this.selectedCounts[name]
    } else {
      this.selectedCounts[name] = nextCount
    }

    this.syncSelection()
  },
  syncRows() {
    this.setData({
      rows: buildRows(this.sourceItems, this.data.searchKeyword)
    })
  },
  syncSelection() {
    const { selectedItems, selectedTotalDucats } = buildSelectionState(this.sourceItems, this.selectedCounts)
    this.setData({
      selectedItems,
      selectedTotalDucats
    })
  }
})
